<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>JavaScript 错误 - throw、try 和 catch</title>
</head>
<body>

<!--try 语句测试代码块的错误。
catch 语句处理错误。
throw 语句创建自定义错误。-->


<!--JavaScript try 和 catch
try 语句允许我们定义在执行时进行错误测试的代码块。
catch 语句允许我们定义当 try 代码块发生错误时，所执行的代码块。
JavaScript 语句 try 和 catch 是成对出现的。-->
<script>
    var txt = "";
    function message() {
        try {
            adddlert("Welcome guest!");
        }
        catch (err){
            txt="本页有一个错误。\n\n";
            txt+="错误描述：" + err.message + "\n\n";
            txt+="点击确定继续。\n\n";
            alert(txt);
        }
    }
</script>
<input type="button" value="查看消息" onclick="message()" /><hr>




<!--Throw 语句
throw 语句允许我们创建自定义错误。
正确的技术术语是：创建或抛出异常（exception）。
如果把 throw 与 try 和 catch 一起使用，那么您能够控制程序流，并生成自定义的错误消息。-->
<p>请输出一个 5 到 10 之间的数字:</p>
<input id="demo" type="text">
<button type="button" onclick="myFunction()">测试输入</button>
<p id="message"></p>
<script>
    function myFunction() {
        var message,x;
        message = document.getElementById("message");
        message.innerHTML = "";
        x = document.getElementById("demo").value;
        try{
            if(x == "")  throw "值为空";
            if(isNaN(x)) throw "不是数字";
            /*x = Number(x);*/
            if(x < 5)    throw "太小";
            if(x > 10)   throw "太大";
        }
        catch(err) {
            message.innerHTML = "错误: " + err;
        }
    }
</script>









</body>
</html>